### ISSUE TITLE
Add all these docgen info into a global array

### ISSUE THREAD

**Issue by arunoda** [kadirahq/babel-plugin-react-docgen#3]
We need maintain a global array which contains all these docgen Info in a single place. This will help us to create a directory of classes.

So, at end of each React class we need to push a code block like this:

```js
class MyButton extends React.Component {
    render() {}
}

if (typeof STORYBOOK_REACT_CLASSES !== 'undefined') {
   STORYBOOK_REACT_CLASSES.push({
     'name': 'MyButton',
     'docgenInfo': {},
     'path': 'path of the component (from the root of the project)'
   });
}
```

This is something optional and enabled with a flag. We also need to get the variable name `STORYBOOK_REACT_CLASSES` from the outside.

**Comment by arunoda** [comment]
Implemented with #5

**Comment by arunoda** [comment]
@madushan1000 could you add how to use this on the docs page.

**Comment by madushan1000** [comment]
Done.
